### ISSUE TITLE
PySide6QtAds.CDockManager.setAutoHideConfigFlag not available in version 4.2.1

### ISSUE THREAD

**Issue by RubendeBruin** [mborgerson/pyside6_qtads#30]
In my application I'm doing:

```python
PySide6QtAds.CDockManager.setAutoHideConfigFlag(
    PySide6QtAds.CDockManager.DefaultAutoHideConfig
)

PySide6QtAds.CDockManager.setAutoHideConfigFlag(
    PySide6QtAds.CDockManager.AutoHideSideBarsIconOnly, True
)
```
this worked fine in 4.1.0.3

However since upgrading to 4.2.1 this raises a `AttributeError: type object 'PySide6QtAds.ads.CDockManager' has no attribute 'setAutoHideConfigFlag'` error.

Is this on purpose? (should I replace it with ` PySide6QtAds.CDockManager.setAutoHideConfigFlags(
        PySide6QtAds.ads.CDockManager.eAutoHideFlag.AutoHideSideBarsIconOnly
    )
` ?

**Comment by mborgerson** [comment]
Thanks for reporting! Looks like it was caused by a change to bindings. Should be fixed now with https://github.com/mborgerson/pyside6_qtads/commit/3ea21bfa7c00041e290c1a4656c6a56d6bc4c77c in release 4.3.0.1.
